
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab1_block1(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW

);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg [9:0] LED_OUTPUT;
reg [3:0] Day0;
reg [3:0] Day1;
reg [3:0] Month0;
reg [3:0] Month1;
reg [3:0] Year0;
reg [3:0] Year1;

//=======================================================
//  Structural coding
//=======================================================
always @ (KEY[0])
	begin
		if(KEY[0] == 0)
			LED_OUTPUT[9:0] = SW[9:0];
		else
			LED_OUTPUT[9:0] = ~SW[9:0];
	end	

always @ (KEY[1])
	begin
		if(KEY[1] == 0)
			begin
				Day0 = 1;
				Day1 = 0;
				Month0 =9;
				Month1 =0;
				Year0 =8;
				Year1 = 9;
			end
		else
			begin
				Day0 = 8;
				Day1 = 0;
				Month0 = 6;
				Month1 =0;
				Year0 =5;
				Year1 = 9;

			end
	end	
//09 01 98
assign LEDR[9:0] = LED_OUTPUT[9:0];
sevensegment inst_0(Year0, 0, 0, 0, HEX0);
sevensegment inst_1(Year1, 0, 0, 0, HEX1);
sevensegment inst_2(Day0, 0, 1, 0, HEX2);
sevensegment inst_3(Day1, 0, 0, 0, HEX3);
sevensegment inst_4(Month0, 0, 1, 0, HEX4);
sevensegment inst_5(Month1, 0, 0, 0, HEX5);

endmodule
