
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab1IntegratedDesign(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

always @ (SW[9:8]) begin
	if( SW[9:8] == 2'b00) begin
		//run code from block 1
	end else if( SW[9:8] == 2'b01) begin
		//run code from block 2
	end else begin
		//run code from block 3
	end
endmodule


endmodule
