
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab1_block1(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW

);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg [9:0] LED_OUTPUT;

//=======================================================
//  Structural coding
//=======================================================
always @ (KEY[0])
	begin
		if(KEY[0] == 0)
			LED_OUTPUT[9:0] = SW[9:0];
		else
			LED_OUTPUT[9:0] = ~SW[9:0];
	end	

// This works:	
assign HEX0[7] = 1'b1;
assign HEX0[6] = 1'b1;
assign HEX0[5] = 1'b1;
assign HEX0[4] = 1'b1;
assign HEX0[3] = 1'b1;
assign HEX0[2] = 1'b1;
assign HEX0[1] = 1'b1;
assign HEX0[0] = 1'b1;

assign HEX1[7:0] = 8'h4;
assign HEX2[7:0] = 8'h5;
assign HEX3 = 8'b_0001_0000;
assign HEX4[7:0] = 8'b_0000_1000;
assign HEX5[7:0] = 8'b_0000_0100;

assign LEDR[9:0] = LED_OUTPUT[9:0];

endmodule
