//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab1_block2(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);


//=======================================================
//  REG/WIRE declarations
//=======================================================


reg [3:0] INPUT_1;
reg [3:0] INPUT_0;

wire [3:0] ABS_1;
wire [3:0] ABS_0;

//=======================================================
//  Structural coding
//=======================================================
assign LEDR[9:0] = 10'b0; // LEDs off

twoscompval abs1(SW[7:4], ABS_1);
twoscompval abs0(SW[3:0], ABS_0);
twoscompval dispSUM(SUM[3:0], SUM_OUT);

sevensegment inst_1SIGN(4'b0, 1'b1, 1'b0, ~SW[7], HEX5);
sevensegment inst_1(A, 1'b0, 1'b0, 1'b0, HEX4);

sevensegment inst_0SIGN(4'b0, 1'b1, 1'b0, ~SW[3], HEX1);
sevensegment inst_0(B, 1'b0, 1'b0, 1'b0, HEX0);

//disable middle 2 displays
sevensegment off_1(4'b0, 1'b1, 1'b0, 1'b1, HEX1);
sevensegment off_0(4'b0, 1'b0, 1'b0, 1'b1, HEX0);


always @ (SW[9:8]) begin
	if( SW[9:8] == 2'b10) begin

	end else if ( SW[9:8] == 2'b11) begin

	end 
end


endmodule
